version: "3"
services:
  backend:
    networks:
      - backend_network
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres:15.4-alpine3.18
    stop_grace_period: "3s"
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
volumes:
  postgres_data:
networks:
  backend_network:
