version: "3"
services:
  backend:
    networks:
      - backend_network
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src
    env_file:
      - ./.env
    command: bash -c "alembic upgrade head && uvicorn backend.main:app --workers 1 --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - db

  db:
    image: postgres:15.4-alpine3.18
    stop_grace_period: "3s"
    networks:
      - backend_network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend_network
    volumes:
      - pg_admin_data:/var/lib/pgadmin
volumes:
  postgres_data:
  pg_admin_data:
networks:
  backend_network:
